import{FormEvent,ReactNode,useEffect,useState}from'react';import{Camera,Check,Image,Scissors,Send,Settings,X}from'lucide-react';
type Tab='MY'|'TODAY'|'ASK';type Guide='hair'|'outfit';
const steps={hair:['왁스는 콩알만큼','손바닥에 투명해질 때까지','뒷머리부터 올리기','앞머리는 남은 양만','끝. 오늘 머리 완성 ✓'],outfit:['화이트 셔츠부터','그레이 슬랙스','셔츠 앞만 살짝 넣기','실버 시계로 끝']};
const Label=({children}:{children:ReactNode})=><div className="label">{children}</div>;
const Link=({children,onClick}:{children:ReactNode,onClick?:()=>void})=><button className="link" onClick={onClick}>{children}</button>;
const Header=({title}:{title:string})=><header><h1>{title}</h1><Settings size={18}/></header>;
export default function App(){const[tab,setTab]=useState<Tab>('MY');const[guide,setGuide]=useState<Guide|null>(null);const[onboard,setOnboard]=useState(false);return <div className="app"><main>{tab==='MY'&&<My today={()=>setTab('TODAY')} report={()=>setOnboard(true)}/>} {tab==='TODAY'&&<Today guide={setGuide}/>} {tab==='ASK'&&<Ask/>}</main><nav>{(['MY','TODAY','ASK']as Tab[]).map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav>{guide&&<Walk kind={guide} close={()=>setGuide(null)}/>} {onboard&&<Onboard close={()=>setOnboard(false)}/>}</div>}
function My({today,report}:{today:()=>void,report:()=>void}){return <div className="screen"><Header title="MY"/><section className="card accent"><Label>STYLE STANDARD</Label><h2>민수님의 스타일 기준</h2><div className="rows"><p><b>COLOR</b><span>SUMMER COOL · 네이비·그레이</span></p><p><b>FRAME</b><span>내추럴 골격 · 세미오버핏</span></p><p><b>SKIN</b><span>지성·수분 부족 · 이마 넓은 편</span></p></div><Link onClick={report}>전체 진단 리포트 →</Link></section><section className="card"><Label>MY COLOR</Label><p className="sub">잘 받는 색</p><div className="chips good">{['#1b2a44','#4b5d75','#8ca0b8','#c7cfd8','#f1ede6'].map(x=><i style={{background:x}}/>)}</div><p className="sub">피하면 좋은 색</p><div className="chips">{['#e8c36a','#c44a3a','#6e3a1a'].map(x=><i style={{background:x}}/>)}</div></section><section className="card"><Label>MY CONDITION</Label><p className="between"><b>이발 주기</b><span>5주차 / 6주</span></p><div className="progress"><i/></div><p className="between"><b>피부 상태</b><span>수분 부족 · 개선 ↑</span></p></section><section className="card"><Label>TODAY</Label><h3>오늘은 네이비 셔츠로 가세요.</h3><p className="sub">얼굴이 가장 깔끔해 보여요.</p><Link onClick={today}>오늘의 조언 전체 보기 →</Link></section></div>}
function Today({guide}:{guide:(g:Guide)=>void}){const[done,setDone]=useState(false);return <div className="screen"><Header title="TODAY"/><section className="hero accent"><Label>TODAY'S ONE</Label>{done?<div className="center"><Check/><h2>좋아요. 오늘은 이걸로 끝.</h2><p>다음 이발까지 8일 남았어요.</p></div>:<><p className="sub">오늘 할 일</p><h2>선크림 바르기</h2><p className="sub">지성 피부도 수분이 부족하면 더 번들거릴 수 있어요.</p><button className="primary" onClick={()=>setDone(true)}>했어요</button></>}</section><div className="weather">JUL 10 · THU <span>29° · UV 강함</span></div><Title>O U T F I T</Title><div className="grid"><section className="card"><Label>TOP</Label><h3>화이트 반팔 셔츠</h3><p className="sub">쿨톤에 가장 깨끗해 보여요</p></section><section className="card"><Label>BOTTOM</Label><h3>그레이 와이드 슬랙스</h3><p className="sub">내추럴 골격엔 세미와이드</p></section></div><Link onClick={()=>guide('outfit')}>이대로 입는 법 →</Link><Title>H A I R</Title><section className="card accent"><h2>시스루 댄디</h2><p className="sub">이마가 넓은 편이라 앞머리를 살짝 내리는 게 유리해요.</p><small>왁스 콩알만큼 · 아침 3분</small><Link onClick={()=>guide('hair')}>3분 따라 하기 →</Link><div className="notice"><Scissors size={16}/> 이발 5주차 — 슬슬 다듬을 때</div></section><Title>G R O O M I N G</Title><section className="card list"><p>☀️ <b>선크림</b><span>무기자차 · 지성용</span></p><p>💧 <b>수분 세럼</b><span>유분을 잡는 수분</span></p><p>◉ <b>눈썹 정리</b><span>인상을 깔끔하게</span></p></section><Title>P O I N T</Title><section className="point"><Label>TODAY'S ONE</Label><h2>실버 메탈 시계</h2><p>쿨톤엔 골드보다 실버. 이거 하나면 충분해요.</p></section></div>}
function Title({children}:{children:ReactNode}){return <div className="title"><Label>{children}</Label><i/></div>}
function Ask(){const[answer,setAnswer]=useState('');const[q,setQ]=useState('');const submit=(e:FormEvent)=>{e.preventDefault();if(q.trim())setAnswer('소개팅이면 네이비 셔츠와 그레이 슬랙스. 실버 시계 하나면 충분해.')};return <div className="screen"><Header title="ASK"/><h2>무엇이든 물어보세요</h2><p className="sub">급하면 하나만 누르세요.</p><div className="sos">{['머리 망가짐','옷 얼룩','피부 뒤집어짐','비 맞음'].map(x=><button onClick={()=>setAnswer(`괜찮아. ${x}, 3단계면 해결돼.\n1. 건드리지 말기\n2. 물기만 정리하기\n3. 찬바람으로 마무리`)}>{x}<span>바로 해결 →</span></button>)}</div>{answer&&<section className="card accent answer"><Label>형이 말해줄게</Label><h3>{answer.split('\n')[0]}</h3>{answer.split('\n').slice(1).map(x=><p>{x}</p>)}<button className="primary" onClick={()=>setAnswer('')}>했어요</button></section>}<form onSubmit={submit}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="소개팅인데 뭐 입지?"/><button><Send size={17}/></button></form></div>}
function Walk({kind,close}:{kind:Guide,close:()=>void}){const[i,setI]=useState(0);const list=steps[kind];return <div className="overlay"><section className="walk"><button className="close" onClick={close}><X/></button><span className="count">{i+1} / {list.length}</span><Label>{kind.toUpperCase()}</Label><p className="step">STEP {i+1}</p><h2>{list[i]}</h2><p className="sub">짧고 정확하게 따라하세요.</p><button className="primary" onClick={()=>i===list.length-1?close():setI(i+1)}>{i===list.length-1?'했어요':'다음 →'}</button></section></div>}
function Onboard({close}:{close:()=>void}){const[step,setStep]=useState(1);const[pics,setPics]=useState(0);useEffect(()=>{if(step===2){const t=setTimeout(()=>setStep(3),1200);return()=>clearTimeout(t)}},[step]);return <div className="overlay"><section className="walk onboard"><button className="close" onClick={close}><X/></button><span className="count">0{step} / 03</span>{step===1&&<><Label>START</Label><h2>사진 두 장이면 됩니다.</h2><p className="sub">나머진 저희가 알아냅니다.</p><div className="photos"><button onClick={()=>setPics(Math.max(1,pics))}><Camera/>얼굴 사진</button><button onClick={()=>setPics(2)}><Image/>전신 사진</button></div><button className="primary" disabled={pics<2} onClick={()=>setStep(2)}>분석 시작</button></>}{step===2&&<div className="center loading"><i/><h2>분석 중이에요...</h2><p>30초면 끝납니다</p></div>}{step===3&&<><Label>COMPLETE</Label><h2>사진 2장으로 완성한<br/>나만의 스타일 기준</h2><section className="card accent"><b>SUMMER COOL</b><p>여름 쿨톤 · 내추럴 골격</p></section><button className="primary" onClick={close}>MY에서 확인하기</button></>}</section></div>}
